# Generated by Django 5.1.7 on 2025-03-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_remove_shipment_date_received_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='recieve_date',
            new_name='receive_date',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='contact_number',
        ),
    ]
