# Generated by Django 5.1.7 on 2025-03-13 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
        ('shipments', '0004_shipment_created_by_shipmentitem_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
    ]
