# Generated by Django 5.1.7 on 2025-03-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
        ('shipments', '0005_alter_shipmentitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='factories.factory'),
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
