# Generated by Django 5.1.7 on 2025-03-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_factory_delete_factory'),
        ('shipments', '0006_alter_shipmentitem_product'),
    ]

    operations = [
    ]
