# Generated by Django 5.1.7 on 2025-03-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
