# Generated by Django 5.1.7 on 2025-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
