# Generated by Django 5.1.7 on 2025-03-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_date_created_order_created_at'),
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='supermarkets.supermarket'),
        ),
        migrations.DeleteModel(
            name='Supermarket',
        ),
    ]
