# Generated by Django 5.1.7 on 2025-03-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_supermarket_delete_supermarket'),
        ('orders', '0004_alter_orderitem_created_by_user'),
    ]

    operations = [
    ]
