# Generated by Django 5.1.7 on 2025-03-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20250323_0739'),
        ('orders', '0006_alter_orderitem_product'),
    ]

    operations = [
    ]
