# Generated by Django 5.1.7 on 2025-03-23 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_20250323_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receive_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
