# Generated by Django 5.1.7 on 2025-03-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_20250323_1101'),
        ('orders', '0008_order_receive_date'),
    ]

    operations = [
    ]
