# Generated by Django 5.1.7 on 2025-03-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20250322_1034'),
        ('orders', '0008_order_receive_date'),
    ]

    operations = [
    ]
