# Generated by Django 5.1.7 on 2025-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20250323_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
